/*
 * File: jsapp/store/base/courseStore.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.accessTCStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.accessTCModel'
    ],
	
    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            autoSync: true,	
			storeId: 'SabAccessModuleStore',
            model: 'MyApp.model.accessTCModel',
            proxy: {
                type: 'ajax',
                method: 'POST',
                //url: 'data/DataList.php',
				api: {
		            read: 'data/DataList.php',
		        },
                extraParams: {
                	module: 'accessTCModule'
                },
                reader: {
                    type: 'json',
                    idProperty: 'name',
                    successProperty: 'success',
                    messageProperty: 'message',
                    totalProperty: 'total',
                    root: 'data'
                }
		    }
        }, cfg)]);
    }
});
