/*
 * File: jsapp/store/base/courseStore.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.searchcontentStore', {
    extend: 'Ext.data.Store',
    requires: [
    'MyApp.model.searchcontentModel'
    ],
    selectedCourse: 'cou10',
    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            //autoLoad: {start: 0, limit: 5},
            autoSync: true,	
            remoteFilter : true,
            groupField: 'topicName',
            storeId: 'SabSearchContentStore',
            model: 'MyApp.model.searchcontentModel',
            // totalProperty: 'total', // total data, see json output
            //root: 'results',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                method: 'POST',
                url: 'data/DataList.php?module=advsearch',
                reader : {
                    type : 'json',
                    root : 'items',
                    totalProperty : 'total'
                }
			
            }
        }, cfg)]);
    }
});
